url: "http://www.westhousehotelnewyork.com"

# Build settings
default_lang: 'en'
languages: ['en']

exclude: ['sitemap.json']

page_gen:
  - data: 'Blog'
    template: 'blog-single'
    dir: 'westhouse-blog'
  - data: 'Event'
    template: 'event-single'
    dir: 'events-in-nyc'
  - data: 'Amenities'
    template: 'amenities-single'
    dir: 'luxury-hotel-amenities-nyc'
  - data: 'Offers'
    template: 'sample-offer-details'
    dir: 'sample-offers-list'
  - data: 'Dining'
    template: 'dining-single'
    dir: 'dining'
  - data: 'Partners'
    template: 'partners-detail'
    dir: 'partners'
  - data: 'BlogCategory'
    template: 'category-single'
    dir: ''
  - data: 'Partners'
    template: 'partners-detail'
    dir: 'partners'
  - data: 'Offers'
    template: 'offers-single'
    dir: 'westhouse-offers'
  - data: 'VRTour'
    template: 'vr-tour-single'
    dir: 'virtual-tours-2'
  - data: 'Neighborhood-Locations'
    template: 'neighborhood-single'
    dir: 'things-to-do-in-nyc'
